on: push
jobs:  
    first-job:
     runs-on: ubuntu-latest
     container: node:18.16.1-alpine3.17
     steps:
     - run: node --version
     - run: npm --version
     - uses: actions/checkout@v2 
     #-run: echo "daniel, how are you" 
     - name: upload artifact
       uses: actions/upload-artifact@v3
       with:
          name: my-artifact-dan-test
          path: .
           
    